[project]
    dependencies = [
        "aiosqlite",
        "alembic",
        "bcrypt>=4.3.0",
        "databases",
        "falcon",
        "httpie",
        "joserfc>=1.0.4",
        "loguru>=0.7.3",
        "pydantic-settings>=2.8.1",
        "pydantic[email]>=2.11.3",
        "sqlalchemy",
        "uvicorn[standard]",
]
    description = "TODO"
    name = "e-commerce"
    readme = "README.md"
    requires-python = ">=3.12.9"
    version = "0.1.0"

[dependency-groups]
    dev = ["basedpyright", "ruff"]
